name: challenge_movies
version: 1.0.0+1
publish_to: none
description: Flutter technical challenge project
environment: 
  sdk: '>=2.17.3 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.5
  get: 4.6.5
  get_storage: 2.0.3
  intl: 0.17.0
  dartz: 0.10.1
  flutter_feather_icons: 2.0.0+1
  shimmer: 2.0.0
  cached_network_image: 3.2.1
  flutter_rating_bar: 4.0.1
  url_launcher: 6.1.4
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  fonts: 
    - family: NunitoSans
      fonts: 
        - asset: assets/fonts/NunitoSans-Bold.ttf
        - asset: assets/fonts/NunitoSans-Regular.ttf
  assets: 
    - assets/
    - assets/fonts/
    - assets/images/
    -
  uses-material-design: true

